name: Build and deploy docu

on:
  push:
    branches:
      - 'main'
    paths:
      - 'docs/**'
    

permissions:
  contents: write

jobs:
  build-and-deploy-docu:
    name: Build and deploy Docu
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4.7.1
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt -qq update
          pip3 install mkdocs-material mkdocstrings[python] mkdocs-swagger-ui-tag --upgrade

      - name: Build and Deploy docu
        run: |
          mkdocs gh-deploy --force