name: Measure code coverage

on:
  push:
    paths:
      - 'tests/**'
  pull_request:
    branches:
      - 'main'
    paths:
      - 'tests/**'

permissions:
  contents: read

jobs:
  code-coverage:
      name: Code Coverage
      runs-on: ubuntu-22.04
      steps:
        - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

        - uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4.7.1
          with:
            python-version: '3.10'

        - name: Install dependencies
          run: |
            sudo apt -qq update
            sudo apt -qq install -y graphviz
            pip3 install -r requirements.txt
            pip3 install coverage --upgrade
              
        - name: Run Coverage.py
          run: |
            coverage run --omit=tests/*,pfdl_scheduler/parser/PFDL* -m unittest discover -s tests/unit_test
            coverage report
            coverage json
            coverage html