name: Tests

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

permissions:
  contents: read

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4.7.1
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt -qq update
          sudo apt -qq install -y graphviz
          pip3 install -r requirements.txt
          pip3 install unittest-xml-reporting --upgrade

      - name: Run Unit Tests
        run: python3 -m xmlrunner discover -s tests/unit_test -v -o tmp/build/unittest-reports

      - uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
        with:
          name: Unit Test results
          path: tmp/build/unittest-reports/*.xml

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4.7.1
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt -qq update
          sudo apt -qq install -y graphviz
          pip3 install -r requirements.txt
          pip3 install unittest-xml-reporting --upgrade

      - name: Run Unit Tests
        run: python3 -m xmlrunner discover -s tests/integration_tests -v -o tmp/build/integrationtest-reports

      - uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
        with:
          name: Integration Test results
          path: tmp/build/integrationtest-reports/*.xml
