name: Tests

on: 
  push:
    paths:
      - 'pfdl_scheduler/**'
  pull_request:
    branches:
      - 'main'
    paths:
      - 'pfdl_scheduler/**'

permissions:
  contents: read

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt -qq update
          sudo apt -qq install -y graphviz
          pip3 install -r requirements.txt
          pip3 install unittest-xml-reporting --upgrade 
  
      - name: Run Unit Tests
        run: python3 -m xmlrunner discover -s tests/unit_test -v -o tmp/build/unittest-reports

      - uses: actions/upload-artifact@v3
        with:
          name: Unit Test results
          path: tmp/build/unittest-reports/*.xml
    
  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt -qq update
          sudo apt -qq install -y graphviz
          pip3 install -r requirements.txt
          pip3 install unittest-xml-reporting --upgrade 

      - name: Run Unit Tests
        run: python3 -m xmlrunner discover -s tests/integration_tests -v -o tmp/build/integrationtest-reports

      - uses: actions/upload-artifact@v3
        with:
          name: Integration Test results
          path: tmp/build/integrationtest-reports/*.xml
